version: "3"
services:
  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    env_file:
      - .env

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    image: mern-blog-backend
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./packages/backend:/usr/local/app/packages/backend
    env_file:
      - .env
