version: "3"
services:
  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    env_file:
      - .env

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
      args:
        - PORT=3001
    image: mern-blog-backend
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./packages/backend:/usr/local/app/packages/backend
    env_file:
      - .env
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
      args:
        - PORT=3000
    image: mern-blog-frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./packages/frontend:/usr/local/app/packages/frontend
